# Generated by Django 5.0.7 on 2024-07-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meta",
            fields=[
                ("key", models.TextField(primary_key=True, serialize=False)),
                ("value", models.TextField()),
            ],
            options={
                "db_table": "meta",
            },
        ),
    ]
