# For more details, see https://containers.dev/guide/dependabot
version: 2
updates:
  # Maintain dependencies for GitHub Codespaces
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: 'monthly'
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
  # Maintain dependencies for npm/yarn
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
  # Maintain dependencies for Composer
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'monthly'
