[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = ["src", "*.py", "data", "django_backend", "packages", "tests", "xl"]
exclude = [
  "**/node_modules",
  "**/__pycache__",
  "src/experimental",
  "src/typestubs",
  ".cache",
  "dist",
  "**/vendor"
]
ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"

reportMissingImports = "error"
reportMissingTypeStubs = false
extraPaths = ["src", "data", "packages"]

pythonVersion = "3.11"
pythonPlatform = "Windows"

executionEnvironments = [
  # { root = "src/web", pythonVersion = "3.5", pythonPlatform = "Windows", extraPaths = [
  #   "src/service_libs",
  # ], reportMissingImports = "warning" },
  # { root = "src/sdk", pythonVersion = "3.0", extraPaths = [
  #   "src/backend",
  # ] },
  # { root = "src/tests", extraPaths = [
  #   "src/tests/e2e",
  #   "src/sdk",
  # ] },
  { root = "src" }
]
