---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
# install: https://taskfile.dev/installation/

version: '3'

vars:
  PYTHON:
    sh: |
      # use "/bin/py" as main python command
      {{ if eq OS "windows" }}
        echo "\\\\bin\\\\py.cmd"
      {{ else }}
        echo "/bin/py"
      {{ end }}

env:
  PATH: "{{.PWD}}/bin:{{.PATH}}"

dotenv: ['.env', '.env.local']

tasks:
  default:
    silent: true
    cmd: task --list
  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
  dump:
    desc: Dump test
    ignore_error: true
    cmds:
      - echo $PATH
      - echo $PWD
      - which python
      - which python3
      - which py
      - |
          command -v py || command -v python3 || command -v python
  # task install-python
  install-python:
    desc: Install Python dependencies
    cmds:
      - ".{{.PYTHON}} -m ensurepip --upgrade"
      - ".{{.PYTHON}} -m pip install --upgrade pip"
      - ".{{.PYTHON}} -m pip install --upgrade setuptools"
      - ".{{.PYTHON}} -m pip install --upgrade wheel"
      - ".{{.PYTHON}} -m pip install socks"
      - ".{{.PYTHON}} -m pip install -r requirements-base.txt"
      - ".{{.PYTHON}} -m pip install -e file:packages/proxy-checker-python"
      - ".{{.PYTHON}} -m pip install -e file:packages/proxy-hunter-python"
      - ".{{.PYTHON}} -m pip install -e file:packages/rsa-utility"
      - ".{{.PYTHON}} -m pip install -e file:packages/selenium-stealth"
      - ".{{.PYTHON}} -m pip install -e file:packages/netscape-cookies"