---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
# install: https://taskfile.dev/installation/

version: '3'

vars:
  PYTHON:
    sh: |
      # use "/bin/py" as main python command
      {{ if eq OS "windows" }}
        echo "$(pwd)\\bin\\py.cmd"
      {{ else }}
        echo "$(pwd)/bin/py"
      {{ end }}
  RESOLVED_GITHUB_TOKEN:
    sh: |
      # resolve GITHUB_TOKEN from secrets
      if [ ! -z "$GITHUB_TOKEN" ]; then
        echo "$GITHUB_TOKEN"
      elif [ ! -z "$ACCESS_TOKEN" ]; then
        echo "$ACCESS_TOKEN"
      else
        echo ""
      fi
  PROJECT_DIR:
    sh: echo "$(pwd)"

env:
  PATH: '{{.PWD}}/bin:{{.PWD}}/node_modules/.bin:{{.PWD}}/venv/bin:{{.PWD}}/venv/Scripts:{{.PWD}}/vendor/bin:{{.PATH}}'

dotenv: ['.env', '.env.local']

tasks:
  default:
    silent: true
    cmd: task --list
  noop:
    internal: true
    silent: true
    cmd: noop() { :; }
  dump:
    desc: Dump test
    ignore_error: true
    cmds:
      - echo $PATH
      - echo $PWD
      - 'echo "python: {{.PYTHON}}"'
      - 'echo "github token: {{.RESOLVED_GITHUB_TOKEN}}"'

  install-python:
    desc: Install Python dependencies
    cmds:
      - '"{{.PYTHON}}" -m ensurepip --upgrade'
      - '"{{.PYTHON}}" -m pip install --upgrade pip'
      - '"{{.PYTHON}}" -m pip install --upgrade setuptools'
      - '"{{.PYTHON}}" -m pip install --upgrade wheel'
      - '"{{.PYTHON}}" -m pip install socks'
      - '"{{.PYTHON}}" requirements_install.py --generate'
      - '"{{.PYTHON}}" -m pip install -r requirements.txt'
      - '"{{.PYTHON}}" -m pip install -e file:packages/proxy-checker-python'
      - '"{{.PYTHON}}" -m pip install -e file:packages/proxy-hunter-python'
      - '"{{.PYTHON}}" -m pip install -e file:packages/rsa-utility'
      - '"{{.PYTHON}}" -m pip install -e file:packages/selenium-stealth'
      - '"{{.PYTHON}}" -m pip install -e file:packages/netscape-cookies'

  install-php:
    desc: Install PHP dependencies
    env:
      COMPOSER_AUTH: |
        {
          "github-oauth": {
            "github.com": "{{.RESOLVED_GITHUB_TOKEN}}"
          }
        }
    cmds:
      - php composer.phar config github-oauth.github.com "{{.RESOLVED_GITHUB_TOKEN}}"
      - php composer.phar install --no-progress --no-suggest --no-interaction --optimize-autoloader

  install-nodejs:
    desc: Install NodeJS dependencies
    cmds:
      - touch yarn.lock
      - yarn install

  build-nodejs:
    desc: Build NodeJS project
    cmds:
      - rollup -c rollup.project.js
      - rollup -c rollup.php.js
      - rollup -c rollup.whatsapp.js

  build:
    desc: Build all projects
    cmds:
      - task build-nodejs

  fix-perm:
    desc: Fix file permissions (Linux only)
    silent: true
    cmds:
      - |
        if [ "$(uname)" != "Linux" ]; then
          echo "This task can only run on Linux."
          exit 1
        fi

        echo "Fixing permissions in bin/..."

        # Set read/write for owner, readable for group/others
        chmod -R u+rw,go+r,go-w bin/

        # Ensure executable permission for all files (not just dirs)
        find bin/ -type f -exec chmod u+x {} \;

        # Show result
        ls -l bin/
