CREATE TABLE IF NOT EXISTS "proxies" (
                                         "id" INTEGER,
                                         "proxy" TEXT NOT NULL UNIQUE,
                                         "latency" TEXT,
                                         "type" TEXT,
                                         "region" TEXT,
                                         "city" TEXT,
                                         "country" TEXT,
                                         "timezone" TEXT,
                                         "latitude" TEXT,
                                         "longitude" TEXT,
                                         "last_check" TEXT,
                                         "anonymity" TEXT,
                                         "status" TEXT,
                                         "private" TEXT,
                                         "lang" TEXT,
                                         "useragent" TEXT,
                                         "webgl_vendor" TEXT,
                                         "webgl_renderer" TEXT,
                                         "browser_vendor" TEXT,
                                         "username" TEXT,
                                         "password" TEXT,
                                         PRIMARY KEY ("id" AUTOINCREMENT)
    )
