# Generated by Django 5.0.9 on 2025-01-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_userfields_delete_userbalance"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userfields",
            table="user_fields",
        ),
    ]
