#!/bin/sh

# Set CWD to the root directory of the Git repository
CWD=$(git rev-parse --show-toplevel)
if [ $? -ne 0 ]; then
  echo "Error: Not in a Git repository"
  exit 1
fi

# Fix PHP permissions
OS_TYPE=$(uname -s)

if [[ "$OS_TYPE" == *"CYGWIN"* || "$OS_TYPE" == *"MINGW"* || "$OS_TYPE" == *"MSYS"* ]]; then
  echo "WINDOWS"
elif [[ "$OS_TYPE" == "Linux" ]]; then
  # Change to the Git root directory
  cd "$CWD" || exit
  if command -v lsb_release &>/dev/null; then
    if command -v nginx &>/dev/null; then
      chown -R www-data:www-data "$CWD"/*
    else
      echo "Nginx is not installed"
    fi
  else
    echo "lsb_release command not found, unable to determine distribution"
    exit 1
  fi
else
  echo "Unsupported operating system"
  exit 1
fi
