name: Nuitka CI (debug)

on:
  push:
  workflow_dispatch:
    inputs:
      disableCache:
        description: "Disable cache"
        required: false
        default: "false"
        type: boolean
  workflow_call:
    inputs:
      disableCache:
        description: "Disable cache"
        required: false
        default: "false"
        type: boolean
    secrets:
      ACCESS_TOKEN:
        required: true
  schedule:
    - cron: "0 */8 * * *"

concurrency:
  group: nuitka-ci-debug
  cancel-in-progress: false

jobs:
  build:
    if: contains(github.repository, 'php-proxy-hunter') || contains(github.repository, 'android-traffic-exchange')
    runs-on: windows-latest
    env:
      PIP_CACHE_DIR: "${{ github.workspace }}/project/tmp/pip"
      NUITKA_CACHE_DIR: "${{ github.workspace }}/project/tmp/nuitka-cache"
      NODE_OPTIONS: "--max_old_space_size=4096" #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      node_version: 18.x
      php_version: 7.4
      YARN_CHECKSUM_BEHAVIOR: update

    steps:
      - name: Setup Environment Variables
        if: ${{ github.event.inputs.disableCache || 'false' }}
        shell: bash
        run: |
          echo "NUITKA_CACHE_DIR=${{ github.workspace }}/tmp/nuitka-cache" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          repository: dimaslanjaka/traffic-generator
          ref: python
          token: ${{ secrets.ACCESS_TOKEN }}
          lfs: "true"

      - name: Update Submodules
        run: |
          echo "init submodules"
          git submodule init
          git submodule foreach "git submodule init"
          echo "sync submodules"
          git submodule sync
          git submodule foreach "git submodule sync"
          echo "update submodules"
          mkdir -p bin >/dev/null 2>&1
          curl -L https://github.com/dimaslanjaka/bin/raw/master/bin/submodule-install > bin/submodule-install
          rm -rf .git/modules
          bash ./bin/submodule-install
          git lfs track "*.rar"
        shell: bash

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: "x64"

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Get pip cache dir
        id: pip-cache
        run: echo "pip_cache_dir=$(pip cache dir)" >> $GITHUB_ENV

      - name: Setup Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ./dist/
            ./tmp/
            src/*.sqlite*
            src/*.mmdb
            node_modules/
            .yarn/caches/
            .yarn/*.gz
            ./venv/
            ${{ env.pip_cache_dir }}
            ${{ env.NUITKA_CACHE_DIR }}
            *.lock
            *.txt
            package-lock.json
            assets/proxies/
            vendor/
            ${{ env.USERPROFILE }}\AppData\Local\Nuitka\Nuitka\Cache
            $HOME/AppData/Local/Nuitka/Nuitka/Cache
            config/
            .cache/
            working.json
          key: ${{ runner.os }}-nuitka-${{ hashFiles('.husky/hash.txt') }}
          restore-keys: |
            ${{ runner.os }}-nuitka-${{ hashFiles('.husky/hash.txt') }}
            ${{ runner.os }}-nuitka-
            ${{ runner.os }}-php-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - name: Restore Non-cached Files
        run: |
          git restore *.txt

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          corepack enable
          yarn install
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m distutils.core --help
          python3 requirements_install.py

      - name: Download required files
        run: |
          python3 src/geoPlugin.py

      - name: Clean
        run: gulp clean

      - name: Copy
        run: gulp copy

      - name: Build Simple GUI
        run: |
          gulp sgui --debug

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          overwrite: "true"
          name: built
          path: |
            dist/*.exe
            dist/src/*.sqlite*
            dist/src/*.mmdb
            dist/*.json
            dist/*.txt
            dist/*.yml
