name: Proxy Checker

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.tgz"
      - "**/*.gz"
      - "**/release/**"
      - ".github/codeql/*"
      - "**codeql**"
      - "**clean-caches**"
      - "**/yarn.lock"
      - "!**/.git*"
  workflow_dispatch:
    inputs:
      max:
        description: 'The maximum proxies to be checked.'
        required: true
        default: 500
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true
  schedule:
    # Run every hour
    - cron: "0 * * * *"

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  build:
    # only apply for repository has substring `proxy` like `php-proxy-hunter`
    if: contains(github.repository, 'proxy')
    permissions: read-all
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096" #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      node_version: 18.x
      php_version: 7.4
      YARN_CHECKSUM_BEHAVIOR: update

    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{ secrets.ACCESS_TOKEN }}"
          lfs: ""
      - name: update submodules
        run: |
          echo "init submodules"
          git submodule init
          git submodule foreach "git submodule init"
          echo "sync submodules"
          git submodule sync
          git submodule foreach "git submodule sync"
          echo "update submodules"
          mkdir -p bin >/dev/null 2>&1
          curl -L https://github.com/dimaslanjaka/bin/raw/master/bin/submodule-install > bin/submodule-install
          rm -rf .git/modules
          bash ./bin/submodule-install
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
      - run: corepack enable
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_version }}
          extensions: imagick, swoole, mbstring, intl, pecl_http, curl, redis, pdo_mysql, pdo_sqlite, dom, zip, phalcon4, pgsql
          tools: php-cs-fixer, phpunit, composer:v2
          coverage: none
        env:
          fail-fast: true

      - name: Validate composer
        run: php composer.phar validate --strict

      - name: Cache Composer packages
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            vendor/
            tmp/
            config/
            .cache/
            assets/proxies/
            node_modules/
            .yarn/caches/
            proxies.txt
            dead.txt
            proxyChecker.txt
            working.txt
            working.json
            src/database.sqlite
            composer.lock
            yarn.lock
          key: ${{ runner.os }}-php-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          if [ ! -f composer.lock ]; then
              echo "composer.lock not found, running composer install..."
              php composer.phar install --prefer-dist --no-progress
          else
              echo "composer.lock found, running composer update..."
              php composer.phar update --prefer-dist --no-progress
          fi
          if [ ! -f yarn.lock ]; then
              touch yarn.lock
          fi
          yarn install

      - name: Check last execution proxy fetcher
        id: check_last_run
        run: |
          # Check if tmp directory exists
          mkdir -p tmp

          # Check if last fetch timestamp file exists
          if [ -f tmp/last_fetch_timestamp.txt ]; then
            last_fetch=$(cat tmp/last_fetch_timestamp.txt)
            current_time=$(date +%s)
            elapsed_time=$((current_time - last_fetch))
            four_hours=$((4 * 60 * 60))  # 4 hours in seconds

            if [ $elapsed_time -ge $four_hours ]; then
              echo "run_fetcher=true" >> $GITHUB_OUTPUT
            else
              echo "run_fetcher=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "run_fetcher=true" >> $GITHUB_OUTPUT  # Run if file doesn't exist
          fi

      - name: Fetch proxies if needed
        if: steps.check_last_run.outputs.run_fetcher == 'true'
        run: |
          php proxyFetcher.php --admin='true'
          date +%s > tmp/last_fetch_timestamp.txt  # Update last fetch timestamp
          echo "last_fetch_timestamp=$(date +%s)" >> $GITHUB_STATE

      - name: Check proxies
        run: |
          mkdir -p assets/proxies
          mkdir -p tmp
          mkdir -p tmp/runners
          mkdir -p tmp/cookies
          php proxyChecker.php --max='${{ github.event.inputs.max || 500 }}' --admin='true'

      - name: Check last run clean temp files
        id: clean_temp_files
        run: |
          # Check if tmp directory exists
          mkdir -p tmp

          # Check if last clean timestamp file exists
          if [ -f tmp/last_clean_timestamp.txt ]; then
            last_clean=$(cat tmp/last_clean_timestamp.txt)
            current_time=$(date +%s)
            elapsed_time=$((current_time - last_clean))
            one_week=$((7 * 24 * 60 * 60))  # 1 week in seconds

            if [ $elapsed_time -ge $one_week ]; then
              echo "clean_temp=true" >> $GITHUB_OUTPUT
            else
              echo "clean_temp=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "clean_temp=true" >> $GITHUB_OUTPUT  # Clean if file doesn't exist
          fi

      - name: Clean temp files if needed
        if: steps.clean_temp_files.outputs.clean_temp == 'true'
        run: |
          php configCleaner.php
          date +%s > tmp/last_clean_timestamp.txt  # Update last clean timestamp
          echo "last_clean_timestamp=$(date +%s)" >> $GITHUB_STATE

      - name: Print working proxies
        id: working
        run: |
          # Read the JSON file content
          json_content=$(cat working.json)

          # Check if json_content is not empty, null, [], or {}
          if [ -n "$json_content" ] && [ "$json_content" != "null" ] && [ "$json_content" != "[]" ] && [ "$json_content" != "{}" ]; then
            # Escape the JSON content
            escaped_content=$(printf '%q' "$json_content")

            # Send the JSON content to the specified URL
            curl -s -X POST https://sh.webmanajemen.com/proxyCheckerParallel.php -d "proxy=${escaped_content}" > /dev/null 2>&1
            # print working proxies
            echo "$json_content"
            # copy working proxies into public folder
            mkdir -p public/proxies
            cat working.json > public/proxies/working.json
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "working.json is empty or does not contain valid JSON data."
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Set env
        id: set-env
        shell: bash
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
          echo "GITHUB_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "GITHUB_COMMIT_URL=https://github.com/${{github.repository}}/commit/$(echo $GITHUB_SHA)" >> $GITHUB_ENV
          echo "GITHUB_RUNNER_URL=https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}" >> $GITHUB_ENV

      - name: Deploy working proxies
        if: steps.working.outputs.success == 'true'
        working-directory: public
        continue-on-error: true
        run: |
          git add proxies
          git commit -m "update working proxies" -m "commit hash: ${{ env.GITHUB_SHA_SHORT }}" -m "commit url: ${{ env.GITHUB_COMMIT_URL }}" -m "runner: ${{ env.GITHUB_RUNNER_URL }}"
          git push

      - name: Check last run clean github actions cache
        id: clean_github_actions_cache
        run: |
          # Check if tmp directory exists
          mkdir -p tmp

          # Check if last clean timestamp file exists
          if [ -f tmp/last_ci_cache_clean_timestamp.txt ]; then
            last_clean=$(cat tmp/last_ci_cache_clean_timestamp.txt)
            current_time=$(date +%s)
            elapsed_time=$((current_time - last_clean))
            elapsed_time_target=$((1 * 24 * 60 * 60))  # 1 day in seconds

            if [ $elapsed_time -ge $elapsed_time_target ]; then
              echo "clean_temp=true" >> $GITHUB_OUTPUT
            else
              echo "clean_temp=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "clean_temp=true" >> $GITHUB_OUTPUT  # Clean if file doesn't exist
          fi

      - name: Clean github caches if needed
        if: steps.clean_github_actions_cache.outputs.clean_temp == 'true'
        run: |
          bash bin/clear-github-actions-cache
          date +%s > tmp/last_ci_cache_clean_timestamp.txt  # Update last clean timestamp
          echo "last_ci_cache_clean_timestamp=$(date +%s)" >> $GITHUB_STATE